In [ ]:
import numpy as np

#Basics



In [ ]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
a.ndim

1

In [ ]:
b.shape

(2, 3)

In [ ]:
a.dtype

dtype('int16')

#Access elements

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

#specific row
a[1, :]  #[row, column]


array([ 6,  7,  8,  9, 10])

In [ ]:
#specific column
a[:,1]

array([2, 7])

In [ ]:
#[start:end:stepsize]
a[0,1:4:2]

array([2, 4])

In [ ]:
a[1,2] = 15
print(a)

[[ 1  2  3  4  5]
 [ 6  7 15  9 10]]


In [ ]:
#3D
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#Diffferent types of arrays

In [ ]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.full((3,2),10)

array([[10, 10],
       [10, 10],
       [10, 10]])

In [ ]:
#random decimal number
np.random.rand(3,2)

array([[0.77208912, 0.9036397 ],
       [0.3395871 , 0.83924572],
       [0.56973868, 0.31196384]])

In [ ]:
np.random.randint(7, size = (3,3))

array([[1, 2, 4],
       [0, 2, 3],
       [4, 3, 2]])

In [ ]:
#repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#Math Operations


In [ ]:
a = np.array([1,2,3])

In [ ]:
a+2

array([3, 4, 5])

In [ ]:
a*2

array([2, 4, 6])

In [ ]:
a/2

array([0.5, 1. , 1.5])

In [ ]:
b=np.array([2,3,4])
a+b

array([3, 5, 7])

In [ ]:
#stats
stats = np.array([[1,2,3],[4,5,6]])
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats, axis= 1)  #axis 0 - column axis 1= row

array([1, 4])

In [ ]:
np.max(stats)

6

#Reorganize Array

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#vertically stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.stack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
v1>3

array([False, False, False,  True])

#Array Methods

In [ ]:
np.append(a, [7,8,9])


array([1, 2, 3, 7, 8, 9])

In [ ]:
np.insert(a, 1, 5)

array([1, 5, 2, 3])

In [ ]:
np.delete(a, [1])

array([1, 3])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
a.flatten()

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
concat = np.concatenate((a,b))
print(concat)

[1 2 3 4 5 6]
